##############################################################################
# Copyright (c) 2022, Lawrence Livermore National Security, LLC and
# RADIUSS project contributors. See the COPYRIGHT file for details.
#
# SPDX-License-Identifier: (MIT)
##############################################################################

variables:
  SPACK_PATH: "./spack"
  CONFIG_FILE: "default"

# If a configuration file is given, the pipeline is included.
include:
  - local: $CONFIG_FILE
    rules:
      - if: '$CONFIG_FILE != "default"'
  - local: pipeline.yml
    rules:
      - if: '$CONFIG_FILE != "default"'

# We only do one generation per stage because we found conflicts otherwise
stages:
  - setup

# Run a simple job to display instructions when no config name was specified.
no-config-name:
  tags: [shell, ruby]
  rules:
    - if: '$CONFIG_FILE' == "default"
      when: always
    - when: never
  stage: setup
  script:
    - echo "Variable \"CONFIG_FILE\" was not set."
    - echo "\"CONFIG_FILE\" is required and should point to a config directory."

