##############################################################################
# Copyright (c) 2022, Lawrence Livermore National Security, LLC and
# RADIUSS project contributors. See the COPYRIGHT file for details.
#
# SPDX-License-Identifier: (MIT)
##############################################################################

variables:
  SPACK_PATH: ${CI_BUILDS_DIR}/spack
  SPACK_DEBUG: "-d"
  CONFIG_NAME: "umpire"

# We only do one generation per stage because we found conflicts otherwise
stages:
  - setup
  - quartz
  - ruby
  - lassen
  - corona

# Run a simple job to display instructions when no config name was specified.
no-config-name:
  tags: [shell, quartz]
  rules:
    - if: '$CONFIG_NAME == ""'
      when: always
    - when: never
  stage: setup
  script:
    - echo "Variable \"CONFIG_NAME\" was not set."
    - echo "\"CONFIG_NAME\" is required and should point to a config directory."
    - exit 1

# Trigger sub-pipelines:
quartz:
  stage: quartz
  trigger:
    include: .gitlab/quartz.yml
    strategy: depend
    forward:
      pipeline_variables: true
  rules:
    - if: '$CONFIG_NAME == ""'
      when: never
    - when: on_success

ruby:
  stage: ruby
  trigger:
    include: .gitlab/ruby.yml
    strategy: depend
    forward:
      pipeline_variables: true
  rules:
    - if: '$CONFIG_NAME == ""'
      when: never
    - when: on_success

lassen:
  stage: lassen
  trigger:
    include: .gitlab/lassen.yml
    strategy: depend
    forward:
      pipeline_variables: true
  rules:
    - if: '$CONFIG_NAME == ""'
      when: never
    - when: on_success

corona:
  stage: corona
  trigger:
    include: .gitlab/corona.yml
    strategy: depend
    forward:
      pipeline_variables: true
  rules:
    - if: '$CONFIG_NAME == ""'
      when: never
    - when: on_success
