##############################################################################
# Copyright (c) 2022, Lawrence Livermore National Security, LLC and
# RADIUSS project contributors. See the COPYRIGHT file for details.
#
# SPDX-License-Identifier: (MIT)
##############################################################################

stages:
  - default

.on-corona:
  tags: [shell, corona]

corona-default:
  extends: [.build-job-slurm, .on-corona]
  stage: default

include:
  - local: .gitlab/configs/common.yml
