##############################################################################
# Copyright (c) 2022, Lawrence Livermore National Security, LLC and
# RADIUSS project contributors. See the COPYRIGHT file for details.
#
# SPDX-License-Identifier: (MIT)
##############################################################################

stages:
  - default

.on-lassen:
  tags: [shell, lassen]

lassen-default:
  extends: [.build-job-lsf, .on-lassen]
  stage: default

include:
  - local: .gitlab/configs/common.yml
