##############################################################################
# Copyright (c) 2022, Lawrence Livermore National Security, LLC and
# RADIUSS project contributors. See the COPYRIGHT file for details.
#
# SPDX-License-Identifier: (MIT)
##############################################################################

stages:
  - default

.on-quartz:
  tags: [shell, quartz]

quartz-default:
  extends: [.build-job-slurm, .on-quartz]
  stage: default

include:
  - local: .gitlab/configs/common.yml
