##############################################################################
# Copyright (c) 2022, Lawrence Livermore National Security, LLC and
# RADIUSS project contributors. See the COPYRIGHT file for details.
#
# SPDX-License-Identifier: (MIT)
##############################################################################

# Usage: uncomment and replace "demo" with what is appropriate.

variables:
  CONFIG_NAME: "demo"
# Use the umdev LLNL service user to run CI. This prevents from running
# pipelines as an actual user.
  LLNL_SERVICE_USER: "demo"
# Use the service user workspace. Solves permission issues, stores everything
# at the same location whoever triggers a pipeline.
  CUSTOM_CI_BUILDS_DIR: "/usr/workspace/demo/gitlab-runner"
# We place spack in the umpire workspace to clone it only once.
# WARNING: this is not an issue because the jobs run sequentially.
  SPACK_PATH: "/usr/workspace/demo/spack"
# Repository to clone spack from
  SPACK_REPO: "https://github.com/spack/spack.git"
# Ref (commit or branch) to checkout in spack
  SPACK_REF: "c2af154cd24ab3ef501a7efc020f818ef60aa552"
