#!/bin/bash

##############################################################################
# Copyright (c) 2022, Lawrence Livermore National Security, LLC and
# RADIUSS project contributors. See the COPYRIGHT file for details.
#
# SPDX-License-Identifier: (MIT)
##############################################################################

set -e

. configs/${CONFIG_NAME}/ci-variables.bash

spack_path=${SPACK_PATH:-"./spack"}

#[get-spack--]
if [[ ! -d ${spack_path} ]]
then
  mkdir -p ${spack_path}/..
  # A shallow clone is enough, and much faster.
  git clone ${SPACK_REPO} --depth 1 --branch develop ${spack_path}
fi

if [[ ${SPACK_COMMIT} ]]
then
  cd ${spack_path}
  git checkout -b temp
  git branch -D ${SPACK_REF}
  git fetch --depth 1 ${SPACK_REPO} ${SPACK_REF}:${SPACK_REF}
  git checkout ${SPACK_REF}
  git tag ${CI_PIPELINE_ID}
  git branch -D temp
  cd -
else
  cd ${spack_path}
  git fetch --depth 1 ${SPACK_REPO} ${SPACK_REF}
  git checkout ${SPACK_REF}
  git tag ${CI_PIPELINE_ID}
  cd -
fi
#[--get-spack]
