#!/bin/bash

##############################################################################
# Copyright (c) 2022, Lawrence Livermore National Security, LLC and
# RADIUSS project contributors. See the COPYRIGHT file for details.
#
# SPDX-License-Identifier: (MIT)
##############################################################################

if [[ ! -d ${SPACK_PATH} ]]
then
  cd ${SPACK_PATH}
  git apply ${CI_PROJECT_DIR}/patches/spack/user-scope.patch
  git commit -am "Moving user scope in spack directory"
  cd -
else
  echo "\$SPACK_PATH = $SPACK_PATH is not a directory,"
  echo "be sure to run get-spack first."
  exit 1
fi
