#!/bin/bash

##############################################################################
# Copyright (c) 2022, Lawrence Livermore National Security, LLC and
# RADIUSS project contributors. See the COPYRIGHT file for details.
#
# SPDX-License-Identifier: (MIT)
##############################################################################

vars="ENV_NAME SPACK_REF SPACK_REPO SPACK_PATH"

echo "--------------------------------"
echo "---- Variables of interest "
echo "--------------------------------"

for var in ${vars};
do
  echo "---- ${var} = ${!var} "
done

echo "--------------------------------"
