#!/bin/bash

##############################################################################
# Copyright (c) 2022, Lawrence Livermore National Security, LLC and
# RADIUSS project contributors. See the COPYRIGHT file for details.
#
# SPDX-License-Identifier: (MIT)
##############################################################################

set -e

#[rm-spack--]
if [[ ! -d ${SPACK_PARENT_DIR} ]]
then
  echo "Spack directory not found"
else
  rm -rf ${SPACK_PARENT_DIR}
fi
#[--rm-spack]
