##############################################################################
# Copyright (c) 2022, Lawrence Livermore National Security, LLC and
# RADIUSS project contributors. See the COPYRIGHT file for details.
#
# SPDX-License-Identifier: (MIT)
##############################################################################

.build-job-slurm:
  rules:
    # We ignore failure and run all the tests all the time.
    - when: always
  script:
    - if [[ -d ~/.spack ]]; then mv ~/.spack ~/._spack_saved_ci; fi
    - SPACK_PATH=${SPACK_PATH:-"./spack"}
    - scripts/get-spack
    - . ${SPACK_PATH}/share/spack/setup-env.sh
    - srun -N 1 -p pdebug spack -d spec zlib
  # After scripts runs even on failure, so spack config should be left clean
  # WARNING: canceled jobs will not trigger after script...
  after_script:
    - if [[ -d ~/._spack_saved_ci ]]; then rm -rf ~/.spack && mv ~/._spack_saved_ci ~/.spack; fi

.build-job-lsf:
  rules:
    - when: always
  script:
    - if [[ -d ~/.spack ]]; then mv ~/.spack ~/._spack_saved_ci; fi
    - SPACK_PATH=${SPACK_PATH:-"./spack"}
    - scripts/get-spack
    - . ${SPACK_PATH}/share/spack/setup-env.sh
    - lalloc 1 spack -d spec zlib
  after_script:
    - if [[ -d ~/._spack_saved_ci ]]; then rm -rf ~/.spack && mv ~/._spack_saved_ci ~/.spack; fi
